"""initial schema

Revision ID: e78eaa70ce06
Revises: 
Create Date: 2026-06-03 03:45:58.600828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78eaa70ce06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_pregnant_status', ['pregnant_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('follow_up_records', schema=None) as batch_op:
        batch_op.create_index('idx_followup_pregnant_status', ['pregnant_id', 'status'], unique=False)

    with op.batch_alter_table('medical_orders', schema=None) as batch_op:
        batch_op.create_index('idx_order_pregnant_status', ['pregnant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_orders', schema=None) as batch_op:
        batch_op.drop_index('idx_order_pregnant_status')

    with op.batch_alter_table('follow_up_records', schema=None) as batch_op:
        batch_op.drop_index('idx_followup_pregnant_status')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alert_pregnant_status')

    # ### end Alembic commands ###
